import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Hi Guys my name is Amin Yusuf</h1>
      <h2>Work at Lemonilo as Frontend Engineer</h2>
    </>
  );
}
